// client/src/views/Login.vue
<script setup lang="ts">
import { ref } from 'vue'
import UiInput from '../components/ui/UiInput.vue'
import Logo from '../components/Logo.vue'
import UiButton from '../components/ui/UiButton.vue'

const showLoginCode = ref(false)
const email = ref('')
const loginCode = ref('');

const onSubmit = (e: any) => {
  e.preventDefault();
  // TODO send form
  console.log(email.value);
}

</script>

<template>
  <div class="login">
    <div class="login__main">
      <header class="login__header">
        <router-link to="/">
          <logo color-type="dark" />
        </router-link>
      </header>
      <form class="login__content" @submit="onSubmit">
        <ui-input placeholder="Email" type="email" v-model="email" />
        <div v-if="showLoginCode">
          <ui-input placeholder="Login Code" type="password" v-model="loginCode" />
        </div>
        <ui-button type="submit">Login</ui-button>
      </form>
    </div>
  </div>
</template>

<style>
.login {
  display: flex;
  min-height: 100vh;
  align-items: center;
  justify-content: center;
}

.login__main {
  max-width: 400px;
  width: 100%;
}
</style>

// web/src/pages/Login.tsx
import React, { useState } from "react";
// import { useTypedSelector } from '../hooks/useTypedSelector'
import { useActions } from "../hooks/useActions";
import { Link } from "react-router-dom";
import CenterContent from "../components/common/CenterContent";
import Input from "../components/inputs/Input";
import Logo from "../components/common/Logo";
import styles from "./Login.module.css";
import { LogIn } from "react-feather";

const Login: React.FC = () => {
  // const { account } = useTypedSelector(state => state.app)
  const { fetchLogin, fetchApp } = useActions();
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const onSubmit = async (e: any) => {
    console.log(email, "submit");

    e.preventDefault();
    await fetchLogin({ email, password });
    fetchApp();
  };

  const onChangeEmail = (
    e: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>,
  ) => {
    setEmail(e.currentTarget.value || "");
  };

  // const onChangePassword = (
  //   e: React.FormEvent<HTMLInputElement | HTMLTextAreaElement>,
  // ) => {
  //   setPassword(e.currentTarget.value || "");
  // };

  return (
    <CenterContent>
      <div className={styles.content}>
        <header className={styles.header}>
          <Link
            to="/"
            className={styles.logo}
          >
            <Logo
              type="dark"
            />
          </Link>
        </header>
        <form
          onSubmit={onSubmit}
          className={styles.form}
        >
          <div>
            <Input
              type="email"
              placeholder="Email"
              required
              size={"large"}
              onChange={onChangeEmail}
            />
          </div>
          {
            /* <div>
            <Input
              type="password"
              placeholder="password"
              required
              size={"large"}
              onChange={onChangePassword}
            />
          </div> */
          }
          <button
            className={styles.send}
            type="submit"
          >
            <LogIn size={24} />
          </button>
        </form>
      </div>
    </CenterContent>
  );
};

export default Login;
